server:
  port: 8443

  # You can generate a local key-store by using the followig command.
  # keytool -genkey -alias tomcat \
  #  -storetype PKCS12 -keyalg RSA -keysize 2048 \
  #  -keystore keystore.p12 -validity 3650 \
  ssl:
    key-store: keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: tomcat
